### PR TITLE
Add support for loading from a .jshintrc file

### PR DESCRIPTION
**Pull request by briandela**
I generally have my jshint options in a .jshintrc file to make it easy to run from the commanline tool (http://www.jshint.com/docs/). This is a change to allow you to set the jshint options to a path rather than having to define the jshint options in the gulpfile as well as in my jshint file. For example:

``` js
var gulp = require('gulp');
var plato = require('gulp-plato');

gulp.task('default', function () {
    return gulp.src('app.js')
        .pipe(plato('report', {
            jshint: '.jshintrc',
            complexity: {
                trycatch: true
            }
        }));
});
```

This has helped me keep them in sync as I always have to just update the .jshintrc file

### CODE REVIEW

**Comment by sindresorhus** [comment]
The logic for loading jshintrc should be in Plato itself.

**Comment by briandela** [comment]
Plato seems to have this logic for the CLI but not for the API. Looks like it's designed that the caller (e.g. the CLI/gulp-plato) reads from the jshintrc file (https://github.com/es-analysis/plato/blob/master/lib/cli.js#L36) and passes it in to inspect as part of the options (https://github.com/es-analysis/plato/blob/master/lib/cli.js#L48)

**Comment by sindresorhus** [comment]
This should be handled by Plato. Every consumer shouldn't have to care.

Plato also shouldn't reimplement that logic. It should rather use the exposed JSHint method for getting the config (the right way): https://github.com/jshint/jshint/commit/706b9b7b81b4fb42d812cd5f3315a27c9819e6bd 

// @jsoverson

**Comment by baer** [comment]
Thanks for clearing that up - sorry I should have checked closed issues :)

Would you mind if I submit a PR with this info in the readme? Seems like it's tripping a bunch of people up.

**Comment by db6edr** [comment]
@sindresorhus Sorry for not looking into closed issues.

I agree that the fix should be implemented with Plato and have posted a [pull request](https://github.com/es-analysis/plato/pull/107) with them to merge db6edr/plato@a208e3507cc67e4faa35555d7982c0fc2c677dbf. Let's see how fast they are.

I'll bump the plato dependency version here and submit a pull request once my commit has been released.

**Pull request closed without merging**
